apiVersion: v1
kind: Service
metadata:
  name: caomservice
  labels:
    app: caom2repo
    role: service
    tier: backend
spec:
  ports:
  - port: 9001
    targetPort: 9200
    protocol: TCP
    nodePort: 32700
  selector:
    app: caom2repo
    role: main-container
    tier: backend
  type: NodePort