apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearchdeploy
  labels:
   app: elasticsearch
   role: main-deploy
   tier: backend
spec:
  replicas: 1
  strategy: 
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 10
  template:
    metadata:
      labels:
        app: elasticsearch
        role: main-container
        tier: backend
    spec: 
      containers:
      - name: elasticsearch
        image: gcr.io/google_containers/elasticsearch:v2.4.1-2
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo healthy > /tmp/healthy"]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "rm /tmp/healthy && sleep 70s"]
      nodeSelector:
        area: two
      terminationGracePeriodSeconds: 120