apiVersion: v1
kind: Service
metadata:
  name: elasticsearchservice
  labels:
    app: elasticsearch
    role: service
    tier: backend
spec:
  ports:
  - port: 9001
    targetPort: 9200
    protocol: TCP
    nodePort: 32111
  selector:
    app: elasticsearch
    role: main-container
    tier: backend
  type: NodePort