apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginxdeploy
  labels:
   app: nginx
   role: main-deploy
   tier: backend
spec:
  replicas: 1
  strategy: 
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 10
  template:
    metadata:
      labels:
        app: nginx
        role: main-container
        tier: backend
    spec: 
      containers:
      - name: nginx
        image: nginx:1.13.0
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo healthy > /tmp/healthy"]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "rm /tmp/healthy"]
      terminationGracePeriodSeconds: 60